version: "3.6"

volumes:
  db-volume: null

services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=junction
      - MONGO_INITDB_ROOT_USERNAME=junction
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-volume:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12